### ISSUE TITLE
[Bug] Bootup crash, Basic mods

### ISSUE THREAD

**Issue by SylisMC** [Skylortrexler/Sentimentality-2#2]
**Versions / Mod list**

- jumploader-2.1.2
- fabric-api-0.28.4+1.16
- modmenu-1.14.13+build.19
- Sentimentality2-1.0.0
~end of mod list~

**Description**

- Bootup crash (doesn't reach title screen)

**Log**
[latest.log](https://github.com/Skylortrexler/Sentimentality-2/files/5749590/latest.log)

**Comment by skylorbeck** [comment]
Forgot to mention in the original post that Trinkets is required. It's listed now.
