### ISSUE TITLE
[Request] feature toggle in Config

### ISSUE THREAD

**Issue by SylisMC** [Skylortrexler/Sentimentality-2#4]
that's really weird, I'm sorry, I typed out a description but it got deleted?? 

Some features "conflict" with other mods. they don't cause a crash but they can cause gameplay and immersion issues

- **Stonecutter** Charm, & Woodcutter Both add a woodcutter, a completely separate block that does the same thing but keeps the wood and stone separate for immersion I like this better 
- **Dropped items**, there are a few mods that do this, mainly Better Dropped Items, but if they ever expand on their mod, users may want to choose between what features from what mods they use
- **Glass doors** As a builder I really don't like the glass in the doors, and I removed it manually. Minecraft doesn't give you a lot of options for building, and builders will often improvise. For example, I use trap doors for fences, retaining walls, windows, roofs, and more. a lot of these things look kinda stupid with glass in them, its a nice feature, but there are way more places I don't want glass then places I do, maybe a new block would be a nice alternative?
- **tool/weapon variants** I love this, but at the same time, it's a feature that's shown its face more than a few times, and it would be nice to choose what tools you want/don't want. depending on if you just don't like them, or if you want another mod to handle them. I'm personally not a fan of some of the tools, so I disabled the crafting recipe in a datapack but it would of been a lot easier for most people to toggle them in a config file

In general, being able to turn features on/off is really nice for a place to customize their experience. im handy/stubborn enough to work around not having a config file but it's about 10x the work. disabling features with data packs, resource packs, and editing mod jars

**Comment by skylorbeck** [comment]
What features? There are some minor configuration options already.

**Comment by shouxd** [comment]
I second this. Mod is amazing but it'd be perfect if everything was highly customizable!

**Comment by SylisMC** [comment]
I re-commented. im not sure what happened but my description got deleted on me for some reason?

**Comment by skylorbeck** [comment]
Excellent update. Thank you for the suggestions.

**Comment by skylorbeck** [comment]
All added blocks, tools and items are now able to be disabled in config, working on some other things before releasing.

**Comment by skylorbeck** [comment]
1.0.3 is released. Glass doors were removed along with most of the other texture changes. I provided a link to the resource pack that I based those changes on so people can pick and choose what they want instead. The only thing I didn't do was change the stonecutter additions as they are invisible if you don't put wood in the stonecutter.
