### ISSUE TITLE
[Request] Sleepstuff toggle

### ISSUE THREAD

**Issue by SylisMC** [Skylortrexler/Sentimentality-2#6]
thanks for all you work you did on the config file, it will be greatly appreciated by many!

One feature i forgot to bring up was sleeping, there are a lot of mods that interact with sleeping. 
Better sleep, Better sleep plus. home camp,  ect. 

On my modpack for example, setting spawn point has been moved to campfires. and beds are used purely to fast forward (not skip) through the night, the more players sleeping, the faster the night is accelerated
Being able to turn off sleep voting would be helpful as well

**Comment by skylorbeck** [comment]
I can't believe I forgot that one. Took ten seconds to implement the code. Adding to the lang file and uploading asap

**Comment by skylorbeck** [comment]
uploaded 1.0.4

**Comment by SylisMC** [comment]
Awesome stuff! thank you kindly
