### ISSUE TITLE
[Idea] Smooth perspective shifting

### ISSUE THREAD

**Issue by SylisMC** [Skylortrexler/Sentimentality-2#8]
A smooth transition between first and 3rd person view. Much like [Nimble](https://www.curseforge.com/minecraft/mc-mods/nimble)

**Comment by skylorbeck** [comment]
It looks like it deleted your post again

**Comment by SylisMC** [comment]
-.- ill rewrite it

**Comment by skylorbeck** [comment]
Wow that's pretty awesome. I'll add it to my list but no promises, it looks pretty complex.

**Comment by SylisMC** [comment]
I think the description issue is happening when i change the name of the post before posting it, i dont know why but something funky is going on
